resources:
 - name: gitresource
   type: GitRepo
   configuration:
     path: ~rahulnlb1/test-fork
     gitProvider: github
     buildOn:
      commit: false
      pullRequestCreate: true
      pullRequestClose: true
     branches:
       include: ^{{gitBranch}}$

pipelines:
 - name: sleep_pipeline
   steps:
     - name: step1
       type: Bash
       configuration:
         inputResources:
           - name: gitresource
       execution:
         onExecute:
           - echo "hello test world updated 2 1"
